### ISSUE TITLE
Email templates and blocks master list

### ISSUE THREAD

**Issue by joshuatf** [Aljullu/woocommerce-gutenberg-emails#3]
Email templates are made up of a series of action hooks, conditionals, and placeholder variables.  Most of the action hooks will be full-sized blocks, while placeholders will be inline elements.

~~Instead of creating separate inline blocks for each of the placeholders, creating a single item with multiple properties will probably be easier and more extensible.  E.g., create a block "Order Details" that has properties for the order number, billing name, and date instead of creating 3 separate inline blocks.~~
We should probably keep the same placeholders and options to keep the scope down on this project.

### Distinct blocks
This is a reduced list of all distinct blocks needed.

- [ ] {site_title}
- [ ] Order Details
  * {order_date}
  * {order_number}
  * {order_billing_full_name}
- [ ] Customer Details
  * {user_pass}
  * {user_login}
  * {user_email}
- [ ] {password_generated}
- [ ] `do_action( 'woocommerce_email_header', $email_heading, $email );` #9
- [ ] `do_action( 'woocommerce_email_footer', $email );` #10
- [ ] `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );` #15
- [ ] `do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );`
- [ ] `do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );`
- [ ] condition: `if ( $order->has_status( 'pending' ) ) { ... }`
- [ ] condition: `if ( 'yes' === get_option( 'woocommerce_registration_generate_password' ) && $password_generated ) { ... }`

### Blocks used in all templates

These blocks are used throughout all email templates.

- `do_action( 'woocommerce_email_header', $email_heading, $email );`
- `do_action( 'woocommerce_email_footer', $email );`
- `{site_title}`

### Templates and associated blocks

- [ ] WC_Email_Cancelled_Order
  * {order_date}
  * {order_number}
  * {order_billing_full_name}
  * `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );`
- [ ] WC_Email_Customer_Completed_Order
  * {order_date}
  * {order_number}
  * {order_billing_full_name}
  * `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );`
- [ ] WC_Email_Customer_Invoice
  * condition:`if ( $order->has_status( 'pending' ) ) { ... }`
  * {order_date}
  * {order_number}
  * {order_billing_full_name}
  * `get_checkout_payment_url()`
  * `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );`
- [ ] WC_Email_Customer_New_Account
  * condition: `if ( 'yes' === get_option( 'woocommerce_registration_generate_password' ) && $password_generated ) { ... }`
  * {user_pass}
  * {user_login}
  * {user_email}
  * {order_billing_full_name}
  * {password_generated}
- [ ] WC_Email_Customer_Note
  * {order_date}
  * {order_number}
  * {customer_note}
  * {order_billing_full_name}
  * `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );`
- [ ] WC_Email_Customer_On_Hold_Order
  * {order_date}
  * {order_number}
  * {order_billing_full_name}
  * `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );`
- [ ] WC_Email_Customer_Processing_Order
  * {order_date}
  * {order_number}
  * {order_billing_full_name}
  * `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );`
- [ ] WC_Email_Customer_Refunded_Order
  * {order_date}
  * {order_number}
  * {order_billing_full_name}
  * `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );`
- [ ] WC_Email_Customer_Reset_Password
  * {order_date}
  * {order_number}
  * {order_billing_full_name}
  * {user_id}
  * {user_login}
  * {reset_key}
  * {blogname} (is this any different than {site_title}?)
  * {my_account_lost_password_url}
- [ ] WC_Email_Failed_Order
  * {order_date}
  * {order_number}
  * {order_billing_full_name}
  * `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );`
- [ ] WC_Email_New_Order
  * {order_date}
  * {order_number}
  * {order_billing_full_name}
  * `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );`
  * `do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );`
